theme = "base16_transparent"

[editor]
line-number = "relative"
#true-color = true
#undercurl = true
color-modes = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
[editor.whitespace]
#render = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

