[editor]
scroll-lines = 1
gutters = [ "diff"] #["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

