live_config_reload = true

# import = ["~/.config/alacritty/rose-pine.toml"]
import = ["~/.config/alacritty/tokyo-night.toml"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 16, y = 14 }
opacity = 0.98
decorations = "None"

[font]
normal = { family = "MonoLisa Nerd Font", style="Regular"}
size = 18
