live_config_reload = true

# import = ["~/.config/alacritty/rose-pine.toml"]
import = ["~/.config/alacritty/tokyo-night.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
dynamic_title = false

[font]
normal = { family = "MonoLisa Nerd Font", style="Regular"}
size = 18
