# .bashrc

# prompt
export PS1="\[\033[32m\]\w\[\033[97m\] >\[\033[0m\] "
[ -z "$TOOLBOX_PATH" ] && export PS1="\033[0;31m! $PS1"
export PS1="\[\e]0;\w\a\]$PS1"

# source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# user specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Use bash-completion, if available
# [[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
#     . /usr/share/bash-completion/bash_completion

#  - autocd - change directory without entering the 'cd' command
#  - cdspell - automatically fix directory typos when changing directory
#  - direxpand - automatically expand directory globs when completing
#  - dirspell - automatically fix directory typos when completing
#  - globstar - ** recursive glob
#  - histappend - append to history, don't overwrite
#  - histverify - expand, but don't automatically execute, history expansions
#  - nocaseglob - case-insensitive globbing
#  - no_empty_cmd_completion - do not TAB expand empty lines
shopt -s autocd cdspell direxpand dirspell globstar histappend histverify \
    nocaseglob no_empty_cmd_completion

# history
HISTCONTROL=ignoreboth:erasedups # Ignore and erase duplicates
HISTFILESIZE=99999               # Max size of history file
HISTSIZE=99999                   # Amount of history to preserve
PROMPT_COMMAND="history -a; history -n"

# toolbox function
t() {
    if [ -n "$1" ]; then
        toolbox run "$1"
    else
        toolbox enter
    fi
}

# compress helper
compress() { tar -czf "${1%/}.tar.gz" "${1%/}"; }
alias decompress="tar -xzf"

# cheat helper
cheat() { curl cheat.sh/"$1"; }

# toolbox only
if [ -n "$TOOLBOX_PATH" ]; then
  #env
  export EDITOR=nvim
  export PROMPT_DIRTRIM=2
  export SYSTEMD_PAGER=

  # aliases
  alias g='git'
  alias n='nvim'
  alias l='eza --group-directories-first'
  alias vim='nvim'
  alias lg='lazygit'

  # overwrites
  alias ls='eza --group-directories-first'
fi

