# Model settings
# model: o1-preview
cache-prompts: true

# General settings
vim: true
auto-commits: false
dirty-commits: false
read: CONVENTIONS.md

# Color settings
user-input-color: #e0def4
tool-output-color: #e0def4
tool-error-color: #eb6f92
tool-warning-color: #f6c177
assistant-output-color: #e0def4
code-theme: nord-darker # pygments themes
