# Model settings
# model: gpt-4
cache-prompts: false

# Editor settings
pretty: true
dark-mode: false
pretty: true

# Color settings
user-input-color: #31748f
tool-output-color: #9ccfd8
tool-error-color: #eb6f92
tool-warning-color: #f6c177
assistant-output-color: #c4a7e7
code-theme: solarized-dark

# Behavior settings
auto-commits: true
verbose: false
show-diffs: false
