# Model settings
# model: o1-preview
cache-prompts: true

# General settings
vim: true
auto-commits: false
dirty-commits: false
suggest-shell-commands: true
yes-always: true # max ai controll :)
read: CONVENTIONS.md

# Color settings
pretty: false
user-input-color: #708090
tool-output-color: #7a7a7a
tool-error-color: #D70000
tool-warning-color: #ffaa88
assistant-output-color: #aaaaaa
code-theme: friendly_grayscale # pygments themes
