# Model settings
# model: gpt-4
# temperature: 0.0

# Editor settings
pretty: true
dark_mode: false
use_color: true

# Behavior settings
auto_commits: true
auto_push: false
verbose: false
show_diffs: false

# Color settings
