# Model settings
# model: gpt-4
cache-prompts: false

# Editor settings
pretty: true
dark-mode: false
pretty: true

# Color settings
user-input-color: #31748f
tool-output-color:
tool-error-color: #FF2222
tool-warning-color: #FFA500
assistant-output-color: #0088ff
code-theme: default

# Behavior settings
auto-commits: true
verbose: false
show-diffs: false
