# mac/ linux env
if [[ "$OSTYPE" == "linux"* ]]; then
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
else
    FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
    alias flushdns="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"
fi

# completion
autoload -Uz compinit
unsetopt menu_complete   # do not autoselect the first completion entry
unsetopt flowcontrol
setopt auto_menu         # show completion menu on successive tab press
setopt complete_in_word
setopt always_to_end
autoload -U +X bashcompinit && bashcompinit
# zstyle ':completion:*' use-cache yes
# zstyle ':completion:*' cache-path $ZSH_CACHE_DIR
compinit

source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# PATH
export PATH="$HOME/.local/bin:$PATH"

# env
ELIXIR_ERL_OPTIONS="-kernel shell_history enabled"

# prompt
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
setopt PROMPT_SUBST
PROMPT='%1d%{%F{green}%}$(parse_git_branch)%{%F{none}%} » '

# fzf
FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--color=fg:#c0caf5,bg:#24283b,hl:#ff9e64 \
--color=fg+:#c0caf5,bg+:#292e42,hl+:#ff9e64 \
--color=info:#7aa2f7,prompt:#7dcfff,pointer:#7dcfff \
--color=marker:#9ece6a,spinner:#9ece6a,header:#9ece6a"
eval "$(fzf --zsh)"

# zoxide
eval "$(zoxide init zsh --cmd cd)"

# alias
alias vim="nvim"
alias n="nvim"
alias lg="lazygit"
alias g="git"
alias rmhosts="rm ~/.ssh/known_hosts"
alias bat="bat --style=numbers,changes --theme=base16"
alias cat="bat --style=plain --pager=never --theme=base16"
alias ls="eza --group-directories-first"
alias rt="wezterm cli set-tab-title"

