# mac/ linux env
if [[ "$OSTYPE" == "linux"* ]]; then
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
else
    FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
    source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    alias flushdns="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"
fi

#env
export EDITOR="nvim"
export PROMPT_DIRTRIM=2
export NODE_NO_WARNINGS=1 # disable node warnings / "punycode is deprecated"

# PATH
export PATH="$HOME/.local/bin:$PATH"

# completion
autoload -Uz compinit
unsetopt menu_complete   # do not autoselect the first completion entry
unsetopt flowcontrol
setopt auto_menu         # show completion menu on successive tab press
setopt complete_in_word
setopt always_to_end
autoload -U +X bashcompinit && bashcompinit
# zstyle ':completion:*' use-cache yes
# zstyle ':completion:*' cache-path $ZSH_CACHE_DIR
compinit

# prompt
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
setopt PROMPT_SUBST
PROMPT='%1d%{%F{green}%}$(parse_git_branch)%{%F{none}%} » '

# zoxide
eval "$(zoxide init zsh)"

# Java + Android
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# alias
alias vim="nvim"
alias n="nvim"
alias lg="lazygit"
alias g="git"
alias lt="ls -lt"
alias ll="ls -lah"
alias ls="ls --color"

# functions
compress() { tar -czf "${1%/}.tar.gz" "${1%/}"; }
decompress() { tar -xzf "${1%/}" }
cheat() { curl cht.sh/"$(sed 's/ /+/g' <<< "$@")"; }
cheatq() { curl cht.sh/"$(sed 's/ /+/g' <<< "$@")?Q"; }
yt() {
    # compatible with ios
    yt-dlp --merge-output-format mp4 \
        --format-sort res:720,fps,vcodec:h264,acodec:m4a \
        --embed-thumbnail \
        --add-metadata \
        --embed-metadata \
        --embed-chapters \
        --windows-filenames \
        --abort-on-error \
        --output "%(title)+.100s - %(id)s.%(ext)s"
}



