# homebrew autocompletion
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
autoload -Uz compinit
compinit

# autcomplete
unsetopt menu_complete   # do not autoselect the first completion entry
unsetopt flowcontrol
setopt auto_menu         # show completion menu on successive tab press
setopt complete_in_word
setopt always_to_end

# automatically load bash completion functions
autoload -U +X bashcompinit && bashcompinit

zstyle ':completion:*' use-cache yes
zstyle ':completion:*' cache-path $ZSH_CACHE_DIR

# add paths
PATH="$HOME/.local/bin:$PATH"

# prompt style
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
setopt PROMPT_SUBST
PROMPT='%1d%{%F{green}%}$(parse_git_branch)%{%F{none}%} > '

# addons
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# fzf
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--color=fg:#c0caf5,bg:#24283b,hl:#ff9e64 \
--color=fg+:#c0caf5,bg+:#292e42,hl+:#ff9e64 \
--color=info:#7aa2f7,prompt:#7dcfff,pointer:#7dcfff \
--color=marker:#9ece6a,spinner:#9ece6a,header:#9ece6a"
eval "$(fzf --zsh)"

# alias
alias vim="nvim"
alias n="nvim"
alias lg="lazygit"
alias g="git"
alias ls="ls --color"
alias flushdns="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"
alias rmhosts="rm ~/.ssh/known_hosts"
alias bat="bat --style=numbers,changes --theme=\$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo tokyonight_storm || echo tokyonight_day)"
alias cat="bat --style=plain --theme=\$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo tokyonight_storm || echo tokyonight_day)"
alias ls="eza --group-directories-first"

# zoxide
eval "$(zoxide init zsh)"
